services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: asterbank-oracle

    environment:
      ORACLE_PWD: ${ORACLE_PWD}
      ORACLE_CHARACTERSET: AL32UTF8

    ports:
      - "1521:1521"
      - "5500:5500"

    volumes:
      - oracle-data:/opt/oracle/oradata

    restart: unless-stopped

volumes:
  oracle-data: